name: docker

on:
  push:
    tags:
      - "**"
  workflow_dispatch: {}

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Docker Metadata action
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
