name: docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - 'docker.io'
          - 'public.ecr.aws'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        if: matrix.registry == 'docker.io'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to AWS ECR
        uses: docker/login-action@v2
        if: matrix.registry == 'public.ecr.aws'
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecr: true

      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.registry }}/${{ github.repository }}
